application: barzinganow 
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Handlers define how to route requests to your application.
handlers:

- url: .*  # This regex directs all routes to main.app
  script: main.app

